import Link from "next/link";
import { ReactNode } from "react";

export const nav = [["Product","/product"],["Brokers","/brokers"],["3PLs","/three-pls"],["Carriers","/carriers"],["Integrations","/integrations"],["Pricing","/pricing"]];

export function MarketingHeader(){return <nav className="main"><div className="container row"><Link href="/" style={{fontWeight:800,letterSpacing:".3em"}}>🐕 CLYDE</Link><div className="navLinks">{nav.map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</div><div className="navLinks"><Link href="/login">Log in</Link><Link href="/demo" className="btn btnPrimary">Book a demo</Link></div></div></nav>}
export function MarketingFooter(){return <footer className="footer"><div className="container stack"><div style={{fontWeight:800,letterSpacing:".3em"}}>🐕 CLYDE</div><div>Less inbox. More freight.</div><div className="small">Built by logistics teams, for logistics teams.</div><div className="navLinks">{[...nav,["Demo","/demo"],["Login","/login"]].map(([l,h])=><Link key={h as string} href={h as string}>{l}</Link>)}</div></div></footer>}
export function PageHero({title,copy,cta="Book a demo"}:{title:string;copy:string;cta?:string}){return <section className="hero"><div className="container heroInner"><div className="stack"><p style={{margin:0,color:"#9fc0ff",fontWeight:600}}>Less inbox. More freight.</p><h1 className="h2" style={{margin:0}}>{title}</h1><p className="lead" style={{maxWidth:680,margin:0}}>{copy}</p><div><Link href="/demo" className="btn btnPrimary">{cta}</Link></div></div><div className="darkCard"><p style={{margin:0}}>Replace with branded freight imagery or product UI mockups from <code>/public/images</code>.</p></div></div></section>}
export function SectionHeader({title,copy}:{title:string;copy?:string}){return <div style={{marginBottom:24}}><h2 className="h2" style={{marginTop:0}}>{title}</h2>{copy&&<p className="lead muted" style={{maxWidth:760}}>{copy}</p>}</div>}
export function Cards({items}:{items:{title:string;copy:string;cta?:string;href?:string}[]}){return <div className="grid3">{items.map(i=><div key={i.title} className="card"><h3>{i.title}</h3><p className="muted">{i.copy}</p>{i.cta&&i.href&&<Link href={i.href} style={{color:"#2b6cff",fontWeight:600}}>{i.cta}</Link>}</div>)}</div>}
export function FinalCTA({title,copy}:{title:string;copy:string}){return <section className="section hero"><div className="container stack"><p style={{margin:0,color:"#9fc0ff",fontWeight:600}}>Less inbox. More freight.</p><h2 className="h2" style={{margin:0}}>{title}</h2><p className="lead" style={{maxWidth:760,margin:0}}>{copy}</p><div><Link href="/demo" className="btn btnPrimary">Book a demo</Link></div></div></section>}
export function Layout({children}:{children:ReactNode}){return <><MarketingHeader/>{children}<MarketingFooter/></>}
